---
stages:
  - Build CI image
  - Test and publish

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_VERSION: '20.10.8'

docker build:
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind
  stage: Build CI image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest ci/
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    changes:
      - ci/Dockerfile

build:
  image: $CI_REGISTRY_IMAGE:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: Test and publish
  script:
    - ./build.sh
  artifacts:
    paths:
      - build/bin/universe
