---
image: registry.gitlab.com/jameshiew/universe/ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mkdir build/
  - cd build/
  - conan install .. --build missing
  - cmake ..

build:
  script:
    - make -j 4
